name: Daily Attendance Report

on:
  schedule:
    # KST is UTC+9. Run at 9:35 AM KST and 6:35 PM KST daily.
    # 9:35 AM KST = 00:35 UTC
    # 6:35 PM KST = 09:35 UTC
    # Cron format: minute hour day(month) month day(week)
    - cron: '35 0,9 * * *' # Runs at 00:35 and 09:35 UTC daily

  workflow_dispatch: # Allows manual triggering from GitHub Actions tab
    inputs:
      logLevel:
        description: 'Log level for script run'
        required: false
        default: 'INFO'

jobs:
  run-attendance-report:
    runs-on: ubuntu-latest # Use a standard Linux runner provided by GitHub
    # Optional: Set timeout for the job
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Cache pip dependencies

      - name: Install Google Chrome Stable and Dependencies
        run: |
          echo "Updating package lists..."
          sudo apt-get update -y
          echo "Installing prerequisites for Chrome setup..."
          sudo apt-get install -y wget gnupg software-properties-common
          echo "Adding Google Chrome repository..."
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          echo "Updating package lists again after adding repo..."
          sudo apt-get update -y
          echo "Installing Google Chrome Stable..."
          # Let apt handle most dependencies. Add specific ones only if needed and known to be correct.
          # libasound2t64 is the correct name for libasound2 on Ubuntu 24.04 (noble)
          # Other common ones sometimes needed for headless: libnss3 libxss1 libgconf-2-4 (older)
          # Start minimal and add more *only if* the script fails due to missing libraries.
          sudo apt-get install -y google-chrome-stable libnss3 libasound2t64 # <-- Use libasound2t64
          echo "Verifying Chrome installation..."
          google-chrome-stable --version || echo "Chrome verification failed"

      - name: Install Korean Fonts (Nanum)
        run: |
          echo "Installing Korean fonts..."
          sudo apt-get update -y # Good practice to update before installing
          sudo apt-get install -y fonts-nanum*
          # Rebuild font cache
          echo "Rebuilding font cache..."
          sudo fc-cache -fv
          echo "Font installation complete."

      - name: Install Python dependencies
        run: |
          echo "Installing Python requirements..."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Python dependencies installed."

      - name: Run Attendance Bot Script
        env:
          # Map GitHub secrets to environment variables for the script
          WEBMAIL_USERNAME: ${{ secrets.WEBMAIL_USERNAME }}
          WEBMAIL_PASSWORD: ${{ secrets.WEBMAIL_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # Set Matplotlib cache directory
          MPLCONFIGDIR: ${{ github.workspace }}/.cache/matplotlib
          # Pass log level from manual trigger if provided
          LOG_LEVEL: ${{ github.event.inputs.logLevel || 'INFO' }}
        run: |
          echo "Setting Matplotlib cache directory..."
          mkdir -p $MPLCONFIGDIR
          echo "Running Python script: work_day_bot.py..."
          python work_day_bot.py
          echo "Script execution finished."

      # Upload generated image and screenshots as artifacts for debugging
      - name: Upload generated artifacts
        uses: actions/upload-artifact@v4
        if: always() # Always run this step
        with:
          name: attendance-artifacts-${{ github.run_id }}
          path: |
            *.png  # Upload any PNG file (includes report image and screenshots)
          if-no-files-found: ignore # Don't fail the workflow if no PNG files are found
